package constants;

import uihelpers.Song;

public class STMFileNames {

    public static final Song[] PAPER_MARIO_TTYD_FILE_NAMES = {
            new Song("btl_3dh1_32k.stm", "Grodus Battle"),
            new Song("btl_bpc1_32k.stm", "Shadow Queen Battle (Invincible)"),
            new Song("btl_cap1_32k.stm", "Rawk Hawk Battle"),
            new Song("btl_cbs1_32k.stm", "Event Battle"),
            new Song("btl_die1_32k.stm", "Game Over"),
            new Song("btl_gmm1_32k.stm", "Smorg Battle"),
            new Song("btl_gnb1_32k.stm", "Hooktail Battle"),
            new Song("btl_gns1_32k.stm", "Macho Grubba Battle"),
            new Song("btl_kbs1_32k.stm", "Tutorial Battle"),
            new Song("btl_kpa3_32k.stm", "Bowser Battle"),
            new Song("btl_krt1_32k.stm", "Cortez Battle"),
            new Song("btl_mag1_32k.stm", "Magnus von Grapple Battle"),
            new Song("btl_rpl1_32k.stm", "Doopliss Battle"),
            new Song("btl_win1_32k.stm", "Win Battle"),
            new Song("btl_win2_32k.stm", "Win Battle (without Partner)"),
            new Song("btl_win3_32k.stm", "Level Up"),
            new Song("btl_wit1_32k.stm", "Shadow Queen Battle (Phase 1)"),
            new Song("btl_wom1_32k.stm", "Shadow Sirens Battle"),
            new Song("btl_wth3_32k.stm", "Shadow Queen Battle (Phase 2)"),
            new Song("btl_zak1_32k.stm", "Normal Battle"),
            new Song("btl_zak3_32k.stm", "Mini-Game"),
            new Song("evt_3dh1_32k.stm", "Grodus' Theme"),
            new Song("evt_3rd1_32k.stm", "Lord Crump's Theme"),
            new Song("evt_air1_32k.stm", "Cheep-Cheep Blimp"),
            new Song("evt_ccr1_32k.stm", "Ms. Mowz's Theme"),
            new Song("evt_cld1_32k.stm", "Madame Flurrie"),
            new Song("evt_cok1_32k.stm", "Cooking with Zess T"),
            new Song("evt_dot1_32k.stm", "8-Bit Mario"),
            new Song("evt_ed1_32k.stm", "Peach is Saved"),
            new Song("evt_ed2_32k.stm", "Return to Mushroom Kingdom"),
            new Song("evt_ed3_32k.stm", "Last Look at Rogueport"),
            new Song("evt_ed4_32k.stm", "Here we Go Again"),
            new Song("evt_ed5_32k.stm", "Farewell Rogueport"),
            new Song("evt_egg1_32k.stm", "Bouncing Yoshi Egg"),
            new Song("evt_elmos_app1_32k.stm", "Ghostly Encounter"),
            new Song("evt_fkh1_32k.stm", "Professor Frankly"),
            new Song("evt_gnb1_32k.stm", "Hooktail Flies Over"),
            new Song("evt_gnb3_32k.stm", "Entering Hooktail's Castle"),
            new Song("evt_gnb4_32k.stm", "Hooktail's Theme"),
            new Song("evt_gns1_32k.stm", "Grubba's Theme"),
            new Song("evt_gns2_32k.stm", "Macho Grubba's Theme"),
            new Song("evt_gstship1_32k.stm", "The Black Skull"),
            new Song("evt_huge_gun1_32k.stm", "Blast-off to the Moon"),
            new Song("evt_kik1_32k.stm", "Escape the Falling Ceiling"),
            new Song("evt_kik2_32k.stm", "Ship Under Attack"),
            new Song("evt_kik3_32k.stm", "Ishnail Theme"),
            new Song("evt_kik4_32k.stm", "X-Nauts Attack"),
            new Song("evt_kou1_32k.stm", "All Aboard to Rogueport"),
            new Song("evt_kpa1_32k.stm", "Bowser's Theme"),
            new Song("evt_kts1_32k.stm", "Cortez's Theme"),
            new Song("evt_lec1_32k.stm", "Partner Tutorial"),
            new Song("evt_mag1_32k.stm", "Magnus von Grapple Theme"),
            new Song("evt_mri1_32k.stm", "Mail for the Mario Bros"),
            new Song("evt_mri2_32k.stm", "Mail for the Mario Bros (without Intro)"),
            new Song("evt_nsk1_32k.stm", "Koops' Reunion"),
            new Song("evt_org1_32k.stm", "Sadness and Happiness"),
            new Song("evt_peh1_32k.stm", "Peach's Theme"),
            new Song("evt_prm1_32k.stm", "Black Chest Curse"),
            new Song("evt_pun1_32k.stm", "The Punies"),
            new Song("evt_pvt1_32k.stm", "Jabbies Battle"),
            new Song("evt_pwn1_32k.stm", "Detective Pennington"),
            new Song("evt_qiz1_32k.stm", "Super Fun Quirk Quiz"),
            new Song("evt_qiz2_32k.stm", "Super Fun Quirk Quiz Question"),
            new Song("evt_rit1_32k.stm", "Train Travel"),
            new Song("evt_rui1_32k.stm", "Luigi's Theme"),
            new Song("evt_stc1_32k.stm", "Chapter Cleared"),
            new Song("evt_vce1_32k.stm", "We're Counting on You, Mario"),
            new Song("evt_wit1_32k.stm", "Shadow Sirens"),
            new Song("evt_wit2_32k.stm", "Shadow Queen's Theme"),
            new Song("evt_wlt1_32k.stm", "TEC's Waltz"),
            new Song("ff_adm1_32k.stm", "Ooh Fanfare"),
            new Song("ff_bok1_32k.stm", "Wrong"),
            new Song("ff_crs1_32k.stm", "Glitz Pit Lose"),
            new Song("ff_disc_set1_32k.stm", "Grodus' Computer"),
            new Song("ff_get2_32k.stm", "Special Item Get"),
            new Song("ff_get3_32k.stm", "Badge Get"),
            new Song("ff_get4_32k.stm", "Item Get"),
            new Song("ff_get6_32k.stm", "Star Piece Get"),
            new Song("ff_get8_32k.stm", "New Party Member"),
            new Song("ff_kpa1_32k.stm", "Super Bowser Bros. (Clear)"),
            new Song("ff_kpa2_32k.stm", "Super Bowser Bros. (Lose Life)"),
            new Song("ff_mail_chakusin1_32k.stm", "Peach's E-Mail"),
            new Song("ff_mail_chakusin2_32k.stm", "Mystery E-Mail"),
            new Song("ff_mail_chakusin3_32k.stm", "You've Got Mail!"),
            new Song("ff_pow1_32k.stm", "Power-up Partner"),
            new Song("ff_r_apr2_32k.stm", "Doopliss Theme"),
            new Song("ff_scs1_32k.stm", "Puzzle Solved!"),
            new Song("ff_slp1_32k.stm", "Goodnight Mario"),
            new Song("ff_spr1_32k.stm", "Enemy Revealed"),
            new Song("ff_spr2_32k.stm", "Whoa!"),
            new Song("ff_spr3_32k.stm", "Missing Fanfare"),
            new Song("ff_stg1_32k.stm", "Crystal Star Get"),
            new Song("ff_stt1_32k.stm", "Chapter Begin"),
            new Song("ff_tou1_32k.stm", "Glitz Pit Intro"),
            new Song("ff_tou2_32k.stm", "Glitz Pit Outro"),
            new Song("ff_tou3_32k.stm", "Rawk Hawk Defeated"),
            new Song("ff_w_apr1_32k.stm", "Shadow Queen's Awakening"),
            new Song("stgk_fld1_32k.stm", "Super Bowser Bros. World 1"),
            new Song("stgk_fld1_up1_32k.stm", "Super Bowser Bros. World 1 (Hurry Up)"),
            new Song("stgk_fld1_up2_32k.stm", "Super Bowser Bros. World 1 (Hurry Up) (without Intro)"),
            new Song("stgk_fld2_32k.stm", "Super Bowser Bros. World 2"),
            new Song("stgk_fld2_up1_32k.stm", "Super Bowser Bros. World 2 (Hurry Up)"),
            new Song("stgk_fld3_32k.stm", "Super Bowser Bros. World 3"),
            new Song("stgk_fld3_up1_32k.stm", "Super Bowser Bros. World 3 (Hurry Up)"),
            new Song("stg_bmm1_32k.stm", "Fahr Outpost"),
            new Song("stg_dim1_32k.stm", "Creepy Steeple"),
            new Song("stg_dor1_32k.stm", "Petal Meadows"),
            new Song("stg_duk1_32k.stm", "Pirate's Grotto"),
            new Song("stg_eki1_32k.stm", "Riverside Station (Unused)"),
            new Song("stg_fsg1_32k.stm", "Boggly Woods"),
            new Song("stg_gnb1_32k.stm", "Hooktail's Castle"),
            new Song("stg_gor1_32k.stm", "Pianta Parlor"),
            new Song("stg_gor2_32k.stm", "Rogueport"),
            new Song("stg_gra1_32k.stm", "Twilight Trail"),
            new Song("stg_gtm1_32k.stm", "The Moon"),
            new Song("stg_hom1_32k.stm", "Riverside Station"),
            new Song("stg_kpa1_32k.stm", "Bowser's Castle"),
            new Song("stg_kpa3_32k.stm", "Super Bowser Bros. (Invincibility)"),
            new Song("stg_ldn1_32k.stm", "Palace of Shadow"),
            new Song("stg_ldn2_32k.stm", "Riddle Tower"),
            new Song("stg_ldn3_32k.stm", "Deeper into The Shadows"),
            new Song("stg_mjn1_32k.stm", "Keelhaul Key"),
            new Song("stg_nok1_32k.stm", "Petalburg"),
            new Song("stg_okk1_32k.stm", "The Great Boggly Tree"),
            new Song("stg_pik1_32k.stm", "Poshley Heights"),
            new Song("stg_rsh_a1_32k.stm", "Excess Express Day"),
            new Song("stg_rsh_b1_32k.stm", "Excess Express Night"),
            new Song("stg_rsh_c1_32k.stm", "Excess Express Dusk"),
            new Song("stg_snd1_32k.stm", "Poshley Sanctum"),
            new Song("stg_stn1_32k.stm", "Shhwonk Fortress"),
            new Song("stg_tgm1_32k.stm", "The Glitz Pit"),
            new Song("stg_tik1_32k.stm", "Pit of 100 Trials"),
            new Song("stg_tik2_32k.stm", "Rogueport Sewers"),
            new Song("stg_tik3_32k.stm", "Ruins of the Thousand-Year Door"),
            new Song("stg_tkd1_32k.stm", "Grodus' Room"),
            new Song("stg_tkd2_32k.stm", "X-Naut Fortress"),
            new Song("stg_tog1_32k.stm", "Glitz Pit Mysteries"),
            new Song("stg_ugt1_32k.stm", "Twilight Town"),
            new Song("stg_urg11_32k.stm", "Glitzville"),
            new Song("sys_demo1_32k.stm", "Opening"),
            new Song("sys_demo2_32k.stm", "Prologue"),
            new Song("sys_dig1_32k.stm", "Main Theme (without Intro)"),
            new Song("sys_mmc1_32k.stm", "Demo Title (Unused)"),
            new Song("sys_opn1_32k.stm", "Adventure Starts"),
            new Song("sys_stf1_32k.stm", "Credits"),
            new Song("sys_tit1_32k.stm", "Main Theme")
    };

    public static final Song[] FIRE_EMBLEM_POR_FILE_NAMES = {
            new Song("gcfe_bgm_btl_ashnard_32k.stm", "To Challenge Ashnard 2"),
            new Song("gcfe_bgm_btl_ashnard_32k_lp.stm", "To Challenge Ashnard 1"),
            new Song("gcfe_bgm_btl_boss1_32k.stm", "Holding Your Own"),
            new Song("gcfe_bgm_btl_boss2_32k.stm", "A Mighty Foe"),
            new Song("gcfe_bgm_btl_class_change_32k.stm", "Moving Up"),
            new Song("gcfe_bgm_btl_cp00_32k.stm", "Defensive Battle"),
            new Song("gcfe_bgm_btl_cp01_32k.stm", "The Enemy Draws Near"),
            new Song("gcfe_bgm_btl_dknight_32k.stm", "Against the Black Knight"),
            new Song("gcfe_bgm_btl_pl01_32k.stm", "Clash"),
            new Song("gcfe_bgm_btl_pl02_32k.stm", "Decisive Attack"),
            new Song("gcfe_bgm_dead1_32k.stm", "A Fallen Comrade"),
            new Song("gcfe_bgm_dead2_32k.stm", "Final Farewell"),
            new Song("gcfe_bgm_ed_grand1_32k.stm", "After the War"),
            new Song("gcfe_bgm_ed_staff1_32k.stm", "Eternal Glory"),
            new Song("gcfe_bgm_evt_advance_32k.stm", "Move Out! 2"),
            new Song("gcfe_bgm_evt_anger_32k.stm", "A Grave Fate"),
            new Song("gcfe_bgm_evt_ashnard1_32k.stm", "Burning Ambition"),
            new Song("gcfe_bgm_evt_ashnard2_32k.stm", "Limitless Power"),
            new Song("gcfe_bgm_evt_caineghis1_32k.stm", "Lion King Caineghis"),
            new Song("gcfe_bgm_evt_comical1_32k.stm", "Comical (Unused)"),
            new Song("gcfe_bgm_evt_cp_msg2_32k.stm", "Shadows Materialize"),
            new Song("gcfe_bgm_evt_dein_32k.stm", "Stratagem in Black Armor"),
            new Song("gcfe_bgm_evt_dheginhansea1_32k.stm", "A Trusted Ruler"),
            new Song("gcfe_bgm_evt_distny1_32k.stm", "The Enemy Approaches"),
            new Song("gcfe_bgm_evt_dknight_32k.stm", "The Black Knight"),
            new Song("gcfe_bgm_evt_erincia2_32k.stm", "Dreaming of Home"),
            new Song("gcfe_bgm_evt_erincia_32k.stm", "Beautiful Princess Elincia"),
            new Song("gcfe_bgm_evt_forest1_32k.stm", "Abominable Memory"),
            new Song("gcfe_bgm_evt_forest2_32k.stm", "The White Heron"),
            new Song("gcfe_bgm_evt_happy1_32k.stm", "Wonderful Pirates"),
            new Song("gcfe_bgm_evt_heron2_32k.stm", "Reyson Leanne"),
            new Song("gcfe_bgm_evt_heron_32k.stm", "Painful Wish"),
            new Song("gcfe_bgm_evt_ike1_32k.stm", "His Father's Son"),
            new Song("gcfe_bgm_evt_ike2_32k.stm", "Father's Back"),
            new Song("gcfe_bgm_evt_ike3_2_32k.stm", "Rally the Spirit 2"),
            new Song("gcfe_bgm_evt_ike3_32k.stm", "Rally the Spirit 1"),
            new Song("gcfe_bgm_evt_ina_32k.stm", "To My Love"),
            new Song("gcfe_bgm_evt_kiki_32k.stm", "Plight!"),
            new Song("gcfe_bgm_evt_meet1_32k.stm", "With Us!"),
            new Song("gcfe_bgm_evt_meet2_32k.stm", "Vow"),
            new Song("gcfe_bgm_evt_mist2_32k.stm", "Mist Song"),
            new Song("gcfe_bgm_evt_mist_32k.stm", "Memory of Mom"),
            new Song("gcfe_bgm_evt_naesara1_32k.stm", "On Black Wings"),
            new Song("gcfe_bgm_evt_normal1_32k.stm", "Quiet Days"),
            new Song("gcfe_bgm_evt_oliva1_32k.stm", "Power-hungry Fool"),
            new Song("gcfe_bgm_evt_sadness_32k.stm", "World of Sorrow"),
            new Song("gcfe_bgm_evt_sanaki_32k.stm", "A Messenger"),
            new Song("gcfe_bgm_evt_singeki_32k.stm", "Move Out! 1"),
            new Song("gcfe_bgm_evt_tibarn1_32k.stm", "Brave General, Brave King 1"),
            new Song("gcfe_bgm_evt_tibarn2_32k.stm", "Brave General, Brave King 2"),
            new Song("gcfe_bgm_evt_win_32k.stm", "Victory United 3"),
            new Song("gcfe_bgm_evt_win_bad1_32k.stm", "Bittersweet Victory 1"),
            new Song("gcfe_bgm_evt_win_bad_32k.stm", "Bittersweet Victory 2"),
            new Song("gcfe_bgm_evt_win_good1_32k.stm", "Victory United 1"),
            new Song("gcfe_bgm_evt_win_good2_32k.stm", "Victory United 2"),
            new Song("gcfe_bgm_fase_cp01_32k.stm", "CP Phase 1"),
            new Song("gcfe_bgm_fase_cp02_32k.stm", "CP Phase 2"),
            new Song("gcfe_bgm_fase_friend_32k.stm", "NPC Phase"),
            new Song("gcfe_bgm_fase_help_32k.stm", "Partner Phase"),
            new Song("gcfe_bgm_fase_pl01_32k.stm", "Player Phase 1"),
            new Song("gcfe_bgm_fase_pl02_32k.stm", "Player Phase 2"),
            new Song("gcfe_bgm_fe_theme_32k.stm", "Fire Emblem Theme"),
            new Song("gcfe_bgm_gameover1_32k.stm","Requiem for the Fallen"),
            new Song("gcfe_bgm_gameover2_32k.stm", "Game Over (Unused)"),
            new Song("gcfe_bgm_learn1_32k.stm", "Young Warriors"),
            new Song("gcfe_bgm_map00_32k.stm", "Ike's Resolution"),
            new Song("gcfe_bgm_map00_cut01_32k.stm", "Like Father, Like Son"),
            new Song("gcfe_bgm_map00_cut02_32k.stm", "A Battle and a Beginning"),
            new Song("gcfe_bgm_map00_cut03_32k.stm", "The First Fight"),
            new Song("gcfe_bgm_map01_32k.stm", "Greil Mercenaries"),
            new Song("gcfe_bgm_map02_32k.stm", "Change of Scenery"),
            new Song("gcfe_bgm_map03_32k.stm", "Crimea Attacks"),
            new Song("gcfe_bgm_map04_32k.stm", "Congregation of Ambition"),
            new Song("gcfe_bgm_map_ext_32k.stm", "Side Battle"),
            new Song("gcfe_bgm_map_win_32k.stm", "Victory is Near"),
            new Song("gcfe_bgm_pro1_32k.stm", "March Forward!"),
            new Song("gcfe_bgm_pro2_32k.stm", "Fate Unstoppable"),
            new Song("gcfe_bgm_pro3_32k.stm", "Puzzling Truth"),
            new Song("gcfe_bgm_rbh_sng1_32k.stm", "Life Returns"),
            new Song("gcfe_bgm_select1_32k.stm", "For Victory"),
            new Song("gcfe_bgm_select2_32k.stm", "Rising Morale")
    };

    public static final Song[] CUBIVORE_FILE_NAMES = {
            new Song("mahoujin2_32k.stm", "Magic Portal"),
            new Song("sk_deka_32k.stm", "Big (Deka)"),
            new Song("sk_green_32k.stm", "Green"),
            new Song("sk_kitaeba_32k.stm", "Training"),
            new Song("sk_namadoor_32k.stm", "Symbol Door"),
            new Song("sk_niku_32k.stm", "Meat"),
            new Song("sk_ooboss_32k.stm", "New Greatest Boss"),
            new Song("sk_tyuboss_32k.stm", "New Boss"),
            new Song("tm_boss_fight_32k_lp.stm", "Boss Fight"),
            new Song("tm_dead_32k_lp.stm", "Dead"),
            new Song("tm_ending_32k_lp.stm", "Ending"),
            new Song("tm_e_a_32k_lp.stm", "Theme 1"),
            new Song("tm_e_b_32k_lp.stm", "Theme 2"),
            new Song("tm_e_c_32k_lp.stm", "Theme 3"),
            new Song("tm_e_d_32k_lp.stm", "Theme 4"),
            new Song("tm_e_e_32k_lp.stm", "Rainbow Heaven"),
            new Song("tm_fumei_32k_lp.stm", "Ambiguous"),
            new Song("tm_get_nama2_32k_lp.stm", "Get Symbol!"),
            new Song("tm_mesu_32k_lp.stm", "Mate"),
            new Song("tm_name_entry_32k_lp.stm", "Name Entry"),
            new Song("tm_nemunemu_32k_lp.stm", "Sleep, Sleep"),
            new Song("tm_ooboss_fight_32k_lp.stm", "Greatest Boss Fight"),
            new Song("tm_shuffle_32k_lp.stm", "Shuffle"),
            new Song("tm_stage_change_32k_lp.stm", "Stage Change"),
            new Song("tm_title_32k_lp.stm", "Title")
    };

    public static final String[] NONLOOPING_FILE_NAMES = {
            "btl_die1_32k.stm",
            "btl_win1_32k.stm",
            "btl_win2_32k.stm",
            "evt_ed3_32k.stm",
            "evt_ed4_32k.stm",
            "evt_gnb3_32k.stm",
            "evt_wlt1_32k.stm",
            "ff_adm1_32k.stm",
            "ff_bok1_32k.stm",
            "ff_crs1_32k.stm",
            "ff_disc_set1_32k.stm",
            "ff_get2_32k.stm",
            "ff_get3_32k.stm",
            "ff_get4_32k.stm",
            "ff_get6_32k.stm",
            "ff_get8_32k.stm",
            "ff_kpa1_32k.stm",
            "ff_kpa2_32k.stm",
            "ff_mail_chakusin3_32k.stm",
            "ff_pow1_32k.stm",
            "ff_scs1_32k.stm",
            "ff_slp1_32k.stm",
            "ff_spr1_32k.stm",
            "ff_spr2_32k.stm",
            "ff_spr3_32k.stm",
            "ff_stg1_32k.stm",
            "ff_stt1_32k.stm",
            "ff_tou1_32k.stm",
            "ff_tou2_32k.stm",
            "ff_tou3_32k.stm",
            "ff_w_apr1_32k.stm",
            "gcfe_bgm_evt_heron2_32k.stm",
            "gcfe_bgm_evt_win_32k.stm",
            "gcfe_bgm_evt_win_bad_32k.stm",
            "gcfe_bgm_fase_cp01_32k.stm",
            "gcfe_bgm_fase_cp02_32k.stm",
            "gcfe_bgm_fase_friend_32k.stm",
            "gcfe_bgm_fase_help_32k.stm",
            "gcfe_bgm_fase_pl01_32k.stm",
            "gcfe_bgm_fase_pl02_32k.stm",
            "gcfe_bgm_gameover1_32k.stm",
            "gcfe_bgm_rbh_sng1_32k.stm",
            "mahoujin2_32k.stm",
            "sk_deka_32k.stm",
            "sk_green_32k.stm",
            "sk_kitaeba_32k.stm",
            "sk_namadoor_32k.stm",
            "sk_niku_32k.stm",
            "sk_ooboss_32k.stm",
            "sk_tyuboss_32k.stm",
            "sys_demo1_32k.stm",
            "sys_demo2_32k.stm",
            "sys_opn1_32k.stm",
            "sys_stf1_32k.stm"
    };
}
